use crate::extras::r#loop::{SUMMARY_TRUNCATION_CHARS, plan};
use std::path::PathBuf;

struct LoopTestDataDir {
    path: PathBuf,
    _environment: crate::tests::ScopedProcessEnv,
}

impl Drop for LoopTestDataDir {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.path);
    }
}

fn loop_test_data_dir() -> LoopTestDataDir {
    let dir = std::env::temp_dir().join(format!("zerostack-loop-tests-{}", uuid::Uuid::new_v4()));
    std::fs::create_dir_all(&dir).unwrap();
    let environment = crate::tests::ScopedProcessEnv::set(&[(
        "ZS_DATA_DIR",
        Some(dir.as_os_str().to_os_string()),
    )]);
    LoopTestDataDir {
        path: dir,
        _environment: environment,
    }
}

fn unique_plan_path(label: &str) -> PathBuf {
    std::env::temp_dir().join(format!("zerostack-{label}-{}", uuid::Uuid::new_v4()))
}

// --- LoopState tests ---

#[test]
#[allow(clippy::assertions_on_constants)]
fn test_summary_truncation_constant() {
    // Guards against the constant being set to a nonsensical zero value.
    assert!(SUMMARY_TRUNCATION_CHARS > 0);
}

// --- plan tests ---

#[test]
fn test_plan_exists_on_nonexistent() {
    let tmp = unique_plan_path("plan-nonexistent.md");
    let _ = std::fs::remove_file(&tmp);
    assert!(!plan::plan_exists(&tmp));
}

#[test]
fn test_plan_exists_on_existing() {
    let tmp = unique_plan_path("plan-exists.md");
    std::fs::write(&tmp, "# Test plan").unwrap();
    assert!(plan::plan_exists(&tmp));
    let _ = std::fs::remove_file(&tmp);
}

#[test]
fn test_delete_plan_removes_file() {
    let tmp = unique_plan_path("delete-plan.md");
    std::fs::write(&tmp, "data").unwrap();
    assert!(tmp.exists());
    plan::delete_plan(&tmp);
    assert!(!tmp.exists());
}

#[test]
fn test_delete_plan_nonexistent_does_not_panic() {
    let tmp = unique_plan_path("delete-nonexistent.md");
    let _ = std::fs::remove_file(&tmp);
    plan::delete_plan(&tmp); // should not panic
}

#[tokio::test]
async fn test_handle_startup_no_plan_returns_false() {
    let tmp = unique_plan_path("startup-nonexistent.md");
    let _ = std::fs::remove_file(&tmp);
    let result = plan::handle_startup(&tmp).await.unwrap();
    assert!(!result);
}

// --- transcript tests ---

#[test]
fn test_build_loop_refreshes_generated_bytecode_policy_before_verification() {
    let loop_script = include_str!("../../scripts/loop.sh");
    let verification_policy = include_str!("../../scripts/loop-verification-policy.sh");

    assert_eq!(
        4,
        loop_script.matches("load_verification_policy").count(),
        "define once, load at startup, and reload before both verification passes",
    );
    assert!(verification_policy.contains("*/__pycache__/*|*.pyc|*.pyo"));
    assert!(
        verification_policy.find("path_is_generated_python_bytecode \"$path\" && return 1")
            < verification_policy.find("case \"$path\" in"),
        "generated bytecode must be rejected before surface relevance",
    );
}

#[test]
fn loop_script_invokes_configured_agent_as_a_quoted_array() {
    let loop_script = include_str!("../../scripts/loop.sh");
    assert!(loop_script.contains("read -r -a AGENT_CMD_ARGS"));
    assert!(loop_script.matches("\"${AGENT_CMD_ARGS[@]}\"").count() >= 3);
    assert!(!loop_script.contains("| $AGENT_CMD"));
}

#[cfg(unix)]
#[test]
fn test_workflow_only_headless_relevance_check_executes_embedded_policy() {
    crate::extras::r#loop::verify_workflow_only_headless_relevance().unwrap();

    let workflow = include_str!("../../.github/workflows/ci.yml");
    assert!(
        workflow.contains("run: >-\n          cargo test --locked sandbox::"),
        "the shared sandbox test filter must remain inside a YAML-safe block scalar",
    );
}

#[cfg(all(unix, feature = "goal"))]
#[tokio::test]
async fn goal_verification_stays_interruptible_and_ignores_a_superseded_result() {
    use crate::event::AgentEvent;
    use crate::extras::validation;
    use crate::sandbox::Sandbox;
    use crate::ui::event_handler::{handle_agent_event, handle_goal_verification_event};
    use crate::ui::state::{AgentRunState, ChainState, SlashState, UiContext};
    use clap::Parser;
    use std::time::Duration;

    // `/loop` is a goal preset now, so this guards the machinery that carries
    // what the loop validator's routing used to: verification runs off the
    // event loop, an interrupt reaches only that command, and a result
    // belonging to a superseded round is ignored rather than applied.
    let root = loop_test_data_dir();
    let workspace =
        std::sync::Arc::new(crate::paths::WorkspaceBinding::capture(&root.path).unwrap());
    let mut context = crate::context::load(true);
    context.workspace_root = workspace.root().to_path_buf();
    let cli = crate::cli::Cli::parse_from([
        "mini-agent",
        "--no-session",
        "--no-sandbox",
        "--shell",
        "/bin/sh",
    ]);
    let cfg = crate::config::Config::default();
    let mut session = crate::session::Session::new("openrouter", "test", 128_000, "");

    let release = root.path.join("release-check");
    let quoted = format!(
        "'{}'",
        release.display().to_string().replace('\'', "'\"'\"'")
    );
    let mut goal = crate::extras::goal::Goal::new("verify something", Vec::new()).unwrap();
    goal.judge = crate::extras::goal::JudgePolicy::Off;
    goal.checks
        .push(crate::extras::goal::GoalCheck::new(format!(
            "while [ ! -f {quoted} ]; do sleep 0.01; done"
        )));
    session.goal_store.set(goal, false).unwrap();
    session
        .goal_store
        .append_report(crate::extras::goal::Report {
            status: crate::extras::goal::ReportStatus::Met,
            evidence: Some("claimed".into()),
            blocker: None,
            reason: None,
            question: None,
            round: 1,
            at: compact_str::CompactString::new("now"),
        });

    let client = crate::provider::AnyClient::OpenRouter(
        rig::providers::openrouter::Client::new("unused-test-key").unwrap(),
    );
    let authority = crate::permission::resolve_configured_execution_authority(&cli, &cfg)
        .unwrap()
        .0;
    let sandbox = crate::permission::bind_configured_shell(
        &cli,
        &cfg,
        authority,
        &workspace,
        None,
        Sandbox::new(false, "__missing_goal_test_backend__"),
    )
    .with_workspace_binding(workspace.clone());
    let mut ui = UiContext::new(
        &cli,
        &cfg,
        &mut session,
        &mut context,
        workspace,
        client,
        None,
        None,
        sandbox.clone(),
        None,
    );
    let mut renderer = crate::ui::renderer::Renderer::new().unwrap();
    let slash = SlashState {
        show_reasoning: false,
        reasoning_enabled: false,
        todo_tools_enabled: false,
    };
    let mut chain = ChainState::default();
    let mut run = AgentRunState::default();
    run.goal_round = Some(crate::extras::goal::driver::RoundCollector::new());
    let (tx, mut rx) = tokio::sync::mpsc::channel(8);

    handle_agent_event(
        AgentEvent::Done {
            response: "finished".into(),
            interactions: Vec::new(),
        },
        &mut renderer,
        &mut run,
        &mut ui,
        &slash,
        &mut chain,
        &tx,
    )
    .await
    .unwrap();

    assert!(
        run.is_running && run.pending_goal_gate.is_some(),
        "verification must run off the event loop"
    );
    let stale_id = run.pending_goal_gate.as_ref().unwrap().operation_id;

    let unrelated_release = root.path.join("release-unrelated");
    let quoted_unrelated = format!(
        "'{}'",
        unrelated_release
            .display()
            .to_string()
            .replace('\'', "'\"'\"'")
    );
    let operation = validation::start(
        &sandbox,
        &format!("while [ ! -f {quoted_unrelated} ]; do sleep 0.01; done; printf survived"),
    );
    let unrelated = tokio::spawn(operation.wait());
    tokio::time::timeout(Duration::from_secs(10), async {
        while sandbox.active_group_count() < 2 {
            tokio::time::sleep(Duration::from_millis(5)).await;
        }
    })
    .await
    .expect("both commands must launch");

    // Cancelling the round's verification stops that command and reaps it,
    // rather than dropping the task that owns it and leaving it running.
    run.cancel_validation();
    std::fs::write(&unrelated_release, b"go").unwrap();
    let survivor = tokio::time::timeout(Duration::from_secs(10), unrelated)
        .await
        .expect("the unrelated command must finish")
        .expect("task joined");
    assert_eq!(
        survivor.stdout, b"survived",
        "cancelling one verification must not touch unrelated commands"
    );

    let superseded = crate::event::GoalVerificationEvent {
        operation_id: crate::event::ValidationOperationId(stale_id.0 + 1),
        checks: Some(crate::extras::goal::gate::CheckOutcome {
            all_passed: true,
            failure_tail: None,
            verified: vec![crate::extras::goal::VerificationKind::Checks],
        }),
        judge: None,
        interrupted: false,
    };
    assert!(
        !handle_goal_verification_event(Box::new(superseded), &mut renderer, &mut run, &mut ui)
            .await
            .unwrap(),
        "a result from another round must not be applied"
    );
    assert_eq!(
        ui.session.goal_store.snapshot().unwrap().status,
        crate::extras::goal::GoalStatus::Active,
        "the goal must not be completed by a stale verification"
    );

    std::fs::write(&release, b"go").unwrap();
    while rx.try_recv().is_ok() {}
}
