#!/usr/bin/env python3
"""Mine closed beads with explicit oracles into reproducible gym task files.

The output is the versioned `{schema_version, defaults, tasks}` object that
scripts/gym/train.py and the Rust harness fixture both consume.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

if __package__:
    from .process_capture import OUTPUT_TAIL_BYTES, run_bounded
    from .worktrees import WorktreeError, remove_workspace, run_worktree
else:
    from process_capture import OUTPUT_TAIL_BYTES, run_bounded
    from worktrees import WorktreeError, remove_workspace, run_worktree

SCHEMA_VERSION = 1
MAX_BLOB_BYTES = 256_000
GIT_BLOB_TIMEOUT_SECS = 30
ORACLE_TIMEOUT_SECS = 300
DEFAULT_BUDGETS = {"max_provider_turns": 12, "max_tool_calls": 24, "max_total_tokens": 16000}
# Only these variables reach a mined oracle run, matching the training runner.
BASE_ENV_ALLOWLIST = (
    "PATH",
    "HOME",
    "USER",
    "LOGNAME",
    "LANG",
    "LC_ALL",
    "LC_CTYPE",
    "TERM",
    "TZ",
    "SSL_CERT_DIR",
    "SSL_CERT_FILE",
)


class OracleSetupError(RuntimeError):
    """The oracle could not run, so there is no fail-to-pass evidence."""


def run(argv: list[str], cwd: Path, *, check: bool = True) -> subprocess.CompletedProcess[bytes]:
    result = subprocess.run(argv, cwd=cwd, capture_output=True)
    if check:
        result.check_returncode()
    return result


def out(result: subprocess.CompletedProcess[bytes]) -> str:
    return result.stdout.decode("utf-8", errors="replace")


def tail_text(data: bytes | None, limit: int = OUTPUT_TAIL_BYTES) -> str:
    return data[-limit:].decode("utf-8", errors="replace").strip() if data else ""


def usable_path(name: str) -> bool:
    parts = Path(name).parts
    if not parts or Path(name).is_absolute():
        return False
    return not any(part.startswith(".") for part in parts)


def isolated_env(root: Path) -> dict[str, str]:
    """Curated environment with gym-owned AppPaths, as used during training."""
    env = {name: os.environ[name] for name in BASE_ENV_ALLOWLIST if name in os.environ}
    for directory in ("data", "local", "state", "cache", "config", "credentials", "tmp"):
        (root / directory).mkdir(parents=True, exist_ok=True)
    (root / "config" / "config.toml").write_text(
        "# Generated by scripts/gym/mine_tasks.py; the operator's config.toml is never read.\n", encoding="utf-8"
    )
    env.update(
        {
            "MINI_AGENT_GYM": "1",
            "ZS_CONFIG_DIR": str(root / "config"),
            "ZS_CREDENTIALS_DIR": str(root / "credentials"),
            "ZS_DATA_DIR": str(root / "data"),
            "ZS_LOCAL_DATA_DIR": str(root / "local"),
            "ZS_STATE_DIR": str(root / "state"),
            "ZS_CACHE_DIR": str(root / "cache"),
            "TMPDIR": str(root / "tmp"),
        }
    )
    return env


def read_blob(repo: Path, specification: str) -> bytes | None:
    # Avoid materializing oversized objects even in Git. The capture limit
    # also covers a ref or replacement changing after this size query.
    size = run(["git", "cat-file", "-s", specification], repo, check=False)
    if size.returncode or not size.stdout.strip().isdigit() or int(size.stdout) > MAX_BLOB_BYTES:
        return None
    try:
        result = run_bounded(
            ["git", "cat-file", "blob", specification], repo, dict(os.environ),
            GIT_BLOB_TIMEOUT_SECS, stdout_limit=MAX_BLOB_BYTES,
        )
    except subprocess.TimeoutExpired:
        return None
    if result.returncode or len(result.stdout) > MAX_BLOB_BYTES:
        return None
    return result.stdout


def changed_text_files(repo: Path, parent: str, commit: str) -> tuple[dict[str, str], dict[str, str], list[str]]:
    """Return (initial files, expected files, deleted files) for one commit.

    Only regular-file entries become text overlays; symlink targets are not
    file contents. Blobs are decoded strictly, preserving line endings.
    Renames are reported as delete+add so both sides can be reproduced.
    """
    listing = run(
        ["git", "diff", "--raw", "-z", "--no-abbrev", "--no-renames", "--diff-filter=AMD", parent, commit], repo
    ).stdout.split(b"\0")
    before: dict[str, str] = {}
    after: dict[str, str] = {}
    deleted: list[str] = []
    regular_or_absent = {b"000000", b"100644", b"100755"}
    for header, name_bytes in zip(listing[0::2], listing[1::2]):
        old_mode, new_mode, old_oid, new_oid, _status = header.split()
        old_mode = old_mode.removeprefix(b":")
        if old_mode not in regular_or_absent or new_mode not in regular_or_absent:
            continue
        try:
            name = name_bytes.decode("utf-8")
        except UnicodeDecodeError:
            continue
        if not name or not usable_path(name):
            continue
        added, removed = old_mode == b"000000", new_mode == b"000000"
        old = None if added else read_blob(repo, old_oid.decode("ascii"))
        new = None if removed else read_blob(repo, new_oid.decode("ascii"))
        if (not added and old is None) or (not removed and new is None):
            continue
        try:
            old_text = old.decode("utf-8") if old is not None else None
            new_text = new.decode("utf-8") if new is not None else None
        except UnicodeDecodeError:
            continue
        if removed:
            if old_text is None:
                continue
            before[name] = old_text
            deleted.append(name)
            continue
        if new_text is None:
            continue
        if old_text is not None:
            before[name] = old_text
        after[name] = new_text
    return before, after, sorted(deleted)


def oracle_at(repo: Path, revision: str, command: str) -> bool:
    with tempfile.TemporaryDirectory(prefix="mini-agent-gym-mine-") as directory:
        root = Path(directory)
        worktree = root / "worktree"
        try:
            try:
                added = run_worktree(repo, "add", "--detach", str(worktree), revision)
            except WorktreeError as error:
                raise OracleSetupError(str(error)) from error
            if added.returncode:
                raise OracleSetupError(f"worktree add {revision} failed: {tail_text(added.stderr)}")
            result = run_bounded(
                ["/bin/sh", "-c", command],
                cwd=worktree,
                env=isolated_env(root),
                timeout=ORACLE_TIMEOUT_SECS,
            )
        except subprocess.TimeoutExpired:
            print(f"gym mine: oracle timed out after {ORACLE_TIMEOUT_SECS}s at {revision[:12]}", file=sys.stderr)
            return False
        finally:
            try:
                remove_workspace(repo, worktree)
            except WorktreeError as error:
                raise OracleSetupError(str(error)) from error
        if result.returncode:
            print(
                f"gym mine: oracle exited {result.returncode} at {revision[:12]}: {tail_text(result.stderr)}",
                file=sys.stderr,
            )
        return result.returncode == 0


def beads_hint(repo: Path) -> str:
    try:
        version = out(run(["bd", "version"], repo, check=False)).strip().splitlines()[:1]
    except (OSError, IndexError):
        version = []
    mode = "unknown"
    metadata = repo / ".beads" / "metadata.json"
    if metadata.is_file():
        try:
            mode = str(json.loads(metadata.read_text(encoding="utf-8")).get("dolt_mode", "unknown"))
        except (OSError, json.JSONDecodeError):
            mode = "unreadable"
    return (
        f"bd version: {version[0] if version else 'unknown'}; .beads/metadata.json dolt_mode: {mode}. "
        "Re-run with --beads-json <file> or export the tracker to .beads/issues.jsonl."
    )


def beads_from_file(path: Path) -> list[dict[str, object]]:
    text = path.read_text(encoding="utf-8")
    stripped = text.lstrip()
    if stripped.startswith("["):
        parsed = json.loads(text)
        return [bead for bead in parsed if isinstance(bead, dict)]
    beads: list[dict[str, object]] = []
    for line in text.splitlines():
        if not line.strip():
            continue
        bead = json.loads(line)
        if isinstance(bead, dict):
            beads.append(bead)
    return beads


def load_beads(repo: Path, beads_json: Path | None) -> list[dict[str, object]]:
    """Enumerate beads in a stable order.

    `bd list` documents no ordering and the JSONL export follows write order,
    so `--limit` would otherwise select a different subset from run to run and
    a mined task file would not be reproducible. Sorting by id here is the only
    ordering guarantee `mine()` relies on.
    """
    closed = (bead for bead in collect_beads(repo, beads_json)
              if str(bead.get("status", "closed")) == "closed")
    return sorted(closed, key=lambda bead: str(bead.get("id", "")))


def collect_beads(repo: Path, beads_json: Path | None) -> list[dict[str, object]]:
    """Read beads from `bd`, falling back to an exported JSONL file."""
    fallback = beads_json or (repo / ".beads" / "issues.jsonl")
    if beads_json is not None:
        return beads_from_file(beads_json)
    try:
        result = run(["bd", "list", "--status", "closed", "--json", "--limit", "0"], repo)
        parsed = json.loads(out(result) or "[]")
    except FileNotFoundError:
        print(f"gym mine: bd is not on PATH. {beads_hint(repo)}", file=sys.stderr)
        parsed = None
    except subprocess.CalledProcessError as error:
        print(
            f"gym mine: bd list failed with exit {error.returncode}: {tail_text(error.stderr)}\n{beads_hint(repo)}",
            file=sys.stderr,
        )
        parsed = None
    except json.JSONDecodeError as error:
        print(f"gym mine: bd list produced unparsable JSON ({error}). {beads_hint(repo)}", file=sys.stderr)
        parsed = None
    if parsed is None:
        if not fallback.is_file():
            raise SystemExit(f"gym mine: no bead source available; {fallback} does not exist")
        print(f"gym mine: falling back to {fallback}", file=sys.stderr)
        return beads_from_file(fallback)
    if isinstance(parsed, dict):
        parsed = parsed.get("issues") or parsed.get("results") or []
    if not isinstance(parsed, list):
        raise SystemExit("gym mine: bd list did not return an array of beads")
    return [bead for bead in parsed if isinstance(bead, dict)]


def mined_prompt(bead: dict[str, object]) -> str:
    """Compose an agent prompt from everything the bead actually says.

    The title alone under-specifies a mined task: the description carries the
    reproduction and the intended fix, and `acceptance_criteria` carries the
    definition of done. Sections the bead does not have are omitted rather than
    emitted empty.
    """
    def text(key: str) -> str:
        value = bead.get(key)
        return value.strip() if isinstance(value, str) else ""

    parts = [text("title") or str(bead.get("id", ""))]
    description = text("description")
    if description:
        parts.append(f"Description:\n{description}")
    acceptance = text("acceptance_criteria")
    if acceptance:
        parts.append(f"Acceptance criteria:\n{acceptance}")
    return "\n\n".join(parts)


def normalized_entry(bead_id: str, value: object) -> dict[str, object]:
    entry = {"command": value} if isinstance(value, str) else value
    if not isinstance(entry, dict):
        raise SystemExit(f"gym mine: oracle map entry for {bead_id} must be a command string or an object")
    command = entry.get("command")
    if not isinstance(command, str) or not command.strip():
        raise SystemExit(f"gym mine: oracle map entry for {bead_id} needs a non-empty 'command'")
    return entry


def resolve_commit(repo: Path, bead_id: str, entry: dict[str, object], main_ref: str) -> tuple[str, str]:
    """Return (commit, skip reason). An explicit fix_commit always wins."""
    explicit = entry.get("fix_commit")
    if explicit:
        parsed = run(["git", "rev-parse", "--verify", f"{explicit}^{{commit}}"], repo, check=False)
        if parsed.returncode:
            return "", f"fix_commit {explicit!r} is not a commit in this repository"
        return out(parsed).strip(), ""
    # Match the whole literal ID: .1 must not select .10 or treat '.' as a
    # wildcard. Later exact mentions are follow-ups; --all admits abandoned branches.
    pattern = rf"(^|[^[:alnum:]_.-]){re.escape(bead_id)}([^[:alnum:]_.-]|$)"
    log = run(["git", "log", main_ref, "--format=%H", "--reverse", "--extended-regexp", f"--grep={pattern}"], repo, check=False)
    if log.returncode:
        return "", f"git log {main_ref} failed: {tail_text(log.stderr)}"
    commits = out(log).split()
    if not commits:
        return "", f"no commit reachable from {main_ref} mentions {bead_id}; add an explicit fix_commit to the oracle map"
    return commits[0], ""


def resolve_parent(repo: Path, commit: str, entry: dict[str, object]) -> tuple[str, str]:
    explicit = entry.get("base_commit")
    revision = f"{explicit}^{{commit}}" if explicit else f"{commit}^"
    parsed = run(["git", "rev-parse", "--verify", revision], repo, check=False)
    if parsed.returncode:
        return "", f"cannot resolve base commit {revision!r}: {tail_text(parsed.stderr)}"
    return out(parsed).strip(), ""


def mine(
    repo: Path, oracle_map: dict[str, object], validate: bool, limit: int, main_ref: str, beads_json: Path | None
) -> tuple[list[dict[str, object]], list[str]]:
    beads = load_beads(repo, beads_json)
    tasks: list[dict[str, object]] = []
    skipped: list[str] = []
    for bead in beads:
        bead_id = str(bead.get("id", ""))
        if bead_id not in oracle_map:
            continue
        entry = normalized_entry(bead_id, oracle_map[bead_id])
        command = str(entry["command"])
        commit, reason = resolve_commit(repo, bead_id, entry, main_ref)
        if not commit:
            skipped.append(f"{bead_id}: {reason}")
            continue
        parent, reason = resolve_parent(repo, commit, entry)
        if not parent:
            skipped.append(f"{bead_id}: {reason}")
            continue
        if validate:
            try:
                if oracle_at(repo, parent, command):
                    skipped.append(f"{bead_id}: oracle already passes at base {parent[:12]}")
                    continue
                if not oracle_at(repo, commit, command):
                    skipped.append(f"{bead_id}: oracle does not pass at fix {commit[:12]}")
                    continue
            except OracleSetupError as error:
                skipped.append(f"{bead_id}: {error}")
                continue
        initial, expected, deleted = changed_text_files(repo, parent, commit)
        if not expected:
            skipped.append(f"{bead_id}: no bounded regular UTF-8 text files changed between {parent[:12]} and {commit[:12]}")
            continue
        tasks.append(
            {
                "name": bead_id,
                "prompt": mined_prompt(bead),
                # Validation provenance belongs to this run, not inherited labels.
                "tags": sorted((set(bead.get("labels") or []) - {"fail-to-pass", "validation-skipped"})
                               | {"mined", "fail-to-pass" if validate else "validation-skipped"}),
                "base_commit": parent,
                "initial_files": initial,
                "deleted_files": deleted,
                "oracle": {
                    "command": command,
                    "expected_files": expected,
                    "id": str(entry.get("id") or f"bead:{bead_id}"),
                },
                "library": str(entry.get("library") or "seeds"),
                "fix_commit": commit,
            }
        )
        if len(tasks) >= limit:
            break
    return tasks, skipped


def document(tasks: list[dict[str, object]]) -> dict[str, object]:
    """Wrap mined tasks in the shared `{defaults, tasks}` schema.

    `defaults` carries exactly the field set the Rust harness fixture declares,
    so both readers agree on the shape; the mined per-task extras (base_commit,
    deleted_files, oracle.command, fix_commit) are the runner-only superset.
    """
    return {
        "schema_version": SCHEMA_VERSION,
        "defaults": {
            "prompt": "Fix the described defect in this workspace.",
            "initial_files": {},
            "oracle": {"expected_files": {}, "id": "mined-default"},
            "budgets": dict(DEFAULT_BUDGETS),
            "scripted_provider_turns": {"none": [], "library": []},
            "expected_export": "",
            "library": "seeds",
        },
        "tasks": tasks,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=Path.cwd())
    parser.add_argument("--oracle-map", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--limit", type=int, default=20)
    parser.add_argument("--main-ref", default="main", help="integration branch searched for fix commits")
    parser.add_argument("--beads-json", type=Path, help="read beads from this JSON/JSONL export instead of running bd")
    parser.add_argument("--no-validate", action="store_true")
    args = parser.parse_args()
    repo = args.repo.resolve()
    oracle_map = json.loads(args.oracle_map.read_text(encoding="utf-8"))
    if not isinstance(oracle_map, dict):
        raise SystemExit("gym mine: --oracle-map must be a JSON object keyed by bead id")
    tasks, skipped = mine(repo, oracle_map, not args.no_validate, max(1, args.limit), args.main_ref, args.beads_json)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(document(tasks), indent=2) + "\n", encoding="utf-8")
    for note in skipped:
        print(f"gym mine: skipped {note}", file=sys.stderr)
    qualification = "unvalidated" if args.no_validate else "validated"
    print(f"mined {len(tasks)} {qualification} task(s) into {args.output}; skipped {len(skipped)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
